# Generated by Django 5.2.5 on 2025-09-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_listings_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorized",
                to="auctions.categories",
            ),
        ),
    ]
