# Generated by Django 5.2.5 on 2025-09-02 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_listings_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="lister",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
