# Generated by Django 5.2.5 on 2025-09-02 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listings_lister"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="comment",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="comments",
            name="commenter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
