# Generated by Django 5.2.5 on 2025-09-02 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_comments_comment_alter_comments_commenter"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_on",
                to="auctions.listings",
            ),
        ),
    ]
