# Generated by Django 5.2.5 on 2025-09-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_comments_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
