# Generated by Django 5.2.5 on 2025-09-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_bids_bidder_alter_bids_listing"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together={("user", "listing")},
        ),
    ]
