# Generated by Django 5.2.6 on 2025-09-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_listings_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
