# Generated by Django 5.2.6 on 2025-09-10 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_alter_listings_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="winner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
